### ISSUE TITLE
QCar2 doesn't spawn on the Plane

### ISSUE THREAD

**Issue by svancjan** [quanser/ACC-Competition-2025#5]
It is not possible to spawn the QCar2 entity on the Plane scenario in QLabs using the provided Python script Setup_Competition_Map.py from Base_Scenarios_Python. Usually, the QCar2 entity also spawns with the QCar0 camera attached to it. This camera entity also doesn't spawn.

The QLabs were run on Ubuntu 24.04. 

The screenshots with visible QLabs logs are attached to this issue.

![Image](https://github.com/user-attachments/assets/0fad5d0a-45bc-4326-97d7-f2672ec4b456)
![Image](https://github.com/user-attachments/assets/e6d0077c-6471-4886-a097-7f757672c680)

**Comment by jsp20** [comment]
Stay updated. We have been resolved the issue on the console log that you showed (With the QCar2_workspace terminating). We're working on solving the issue with the QCar not spawning.

**Comment by jsp20** [comment]
We have updated the Quanser Interactive Labs session to fix the issue for the QCar2 not spawning on the open plane map. Please let me know if this works on your end too. If it does I will close the issue.

**Comment by svancjan** [comment]
Can you please provide us with some guidelines on how to correctly apply the fix you created? We tried to update the QLabs from the repository, but the QCar is still not spawning on the Plane.

**Comment by jsp20** [comment]
Yeap absolutely. 

The virtual container image is hosted on docker hub (https://hub.docker.com/r/quanser/acc2025-virtual-qcar2/tags) you can pull the latest version of the virtual qcar2 docker image using the command `docker pull quanser/acc2025-virtual-qcar2:latest ` . This will fix the concern of the simulation engine not running. On the back end the virtual environment has been updated to enable you to spawn the virtual QCar2 on the open plane scenario. You should not need to make updates on your end. If you are able to spawn the QCar on your system the isaac ros container will look like the screenshot attached. 

If you are still having issues with spawning the QCar you can try the following: 

On your Ubuntu 24.04 LTS machine:  

```
sudo apt purge --auto-remove qlabs-unreal quanser-sdk quarc-runtime
sudo apt-get clean 
wget --no-cache https://repo.quanser.com/debian/prerelease/config/configure_repo_prerelease.sh
chmod a+x configure_repo_prerelease.sh
sudo apt update
sudo apt-get install qlabs-unreal python3-quanser-apis  quarc-runtime
```
 
This will update the qlabs install on your system with the latest release.  Once it has been installed, log in with your credentials and try to rerun the virtual qcar2 docker container. 


![Image](https://github.com/user-attachments/assets/c7559fe0-1f4d-4d1e-a43f-5237c768c48b)

**Comment by otakarekk1** [comment]
We performed a fresh installation of QLabs on the new Ubuntu 24 on a different device today. During the installation process, a new error occurred that was not seen previously during installation on other laptops. This error occurs during installation of qlabs-unreal. After inspecting the post-installation script, we determined that this issue arises while executing the binary /usr/sbin/quanser_license_registration. The new version returns a segmentation fault. We also tried using a binary from another laptop, which probably had an older version of the script (with a different size), and this resulted in a timeout.

![Image](https://github.com/user-attachments/assets/697b6183-914a-4314-90ef-9a2b727c77e4)

**Comment by jshuquanser** [comment]
I'm not sure what binary you copied from another laptop (I assume `quanser_license_registration`?). But anyways, I wouldn't recommend you doing that.

Could you try to completely remove the `qlabs-unreal` (and all other quanser's software) installation by doing:
```
sudo apt purge --auto-remove qlabs-unreal python3-quanser-apis  quarc-runtime
```

Then do a fresh install:
```
sudo apt update 
sudo apt-get install qlabs-unreal python3-quanser-apis
```

If you run into any error, please post them here.

**Comment by kodytota** [comment]
Yeah i tried to copy the binary you mentioned, purging and installing did not work either.

**Comment by jshuquanser** [comment]
Can you post the entire output of the `sudo apt-get install` command?

**Comment by kodytota** [comment]
I will post it tomorrow, because its desktop PC, and I do not have access to it at the moment.

**Comment by jshuquanser** [comment]
Created https://github.com/quanser/ACC-Competition-2025/issues/7 to track the qlabs-unreal installation separately, as it is really a separate issue.

Can you confirm whether the suggestion in https://github.com/quanser/ACC-Competition-2025/issues/5#issuecomment-2698997355 resolved the original issue?

**Comment by kubanond** [comment]
Hey, unfortunatelly your fix does not work, i've followed the instructions from https://github.com/quanser/ACC-Competition-2025/issues/5#issuecomment-2698997355 .
I still cant spawn the qcar on the plane, here are screens

![Image](https://github.com/user-attachments/assets/56fb1247-493b-4782-b39c-77d15e266d9e)

![Image](https://github.com/user-attachments/assets/719bb512-929c-4efc-bb05-7fda20a3b4c4)


Here also the output of the update process you mentioned

`sudo apt purge --auto-remove qlabs-unreal quanser-sdk quarc-runtime
sudo apt-get clean 
wget --no-cache https://repo.quanser.com/debian/prerelease/config/configure_repo_prerelease.sh
chmod a+x configure_repo_prerelease.sh
sudo apt update
sudo apt-get install qlabs-unreal python3-quanser-apis  quarc-runtime
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'quanser-sdk' is not installed, so not removed
The following packages will be REMOVED:
  qlabs-unreal* quanser-license-manager* quarc-runtime*
0 upgraded, 0 newly installed, 3 to remove and 35 not upgraded.
After this operation, 1,212 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 153365 files and directories currently installed.)
Removing qlabs-unreal (1.25.062-1) ...
dpkg: warning: while removing qlabs-unreal, directory '/usr/lib/x86_64-linux-gnu/quanser/qlabs' not empty so not removed
Removing quarc-runtime (1.25.062-1) ...
Removing quanser-license-manager (1.25.062-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for shared-mime-info (2.4-4) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
(Reading database ... 153209 files and directories currently installed.)
Purging configuration files for quarc-runtime (1.25.062-1) ...
Purging configuration files for quanser-license-manager (1.25.062-1) ...
--2025-03-08 16:27:01--  https://repo.quanser.com/debian/prerelease/config/configure_repo_prerelease.sh
Resolving repo.quanser.com (repo.quanser.com)... 13.107.246.44, 2620:1ec:bdf::44
Connecting to repo.quanser.com (repo.quanser.com)|13.107.246.44|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 983 [text/plain]
Saving to: ‘configure_repo_prerelease.sh.1’

configure_repo_prerelease.sh.1                 100%[===================================================================================================>]     983  --.-KB/s    in 0s      

2025-03-08 16:27:01 (138 MB/s) - ‘configure_repo_prerelease.sh.1’ saved [983/983]

Hit:1 http://cz.archive.ubuntu.com/ubuntu noble InRelease
Hit:2 http://cz.archive.ubuntu.com/ubuntu noble-updates InRelease                                                                                                                         
Hit:3 http://cz.archive.ubuntu.com/ubuntu noble-backports InRelease                                                                                                                       
Hit:4 https://download.docker.com/linux/ubuntu noble InRelease                                                                                                                            
Get:5 https://nvidia.github.io/libnvidia-container/stable/deb/amd64  InRelease [1,477 B]                                                                                                  
Hit:6 https://repo.quanser.com/debian/prerelease noble InRelease                                                              
Hit:7 https://nvidia.github.io/libnvidia-container/experimental/deb/amd64  InRelease                                   
Hit:8 https://repo.quanser.com/debian/prerelease bionic InRelease                                
Hit:9 https://dl.google.com/linux/chrome/deb stable InRelease                                    
Hit:10 http://security.ubuntu.com/ubuntu noble-security InRelease          
Fetched 1,477 B in 1s (2,447 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
35 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-quanser-apis is already the newest version (1.25.062-1).
The following NEW packages will be installed:
  qlabs-unreal quanser-license-manager quarc-runtime
0 upgraded, 3 newly installed, 0 to remove and 35 not upgraded.
Need to get 1,095 MB of archives.
After this operation, 1,212 MB of additional disk space will be used.
Get:1 https://repo.quanser.com/debian/prerelease noble/main amd64 quanser-license-manager amd64 1.25.062-1 [38.6 kB]
Get:2 https://repo.quanser.com/debian/prerelease noble/main amd64 quarc-runtime amd64 1.25.062-1 [146 kB]
Get:3 https://repo.quanser.com/debian/prerelease bionic/main amd64 qlabs-unreal amd64 1.25.062-1 [1,094 MB]
Fetched 1,095 MB in 18s (60.0 MB/s)                                                                                                                                                       
Selecting previously unselected package quanser-license-manager.
(Reading database ... 153209 files and directories currently installed.)
Preparing to unpack .../quanser-license-manager_1.25.062-1_amd64.deb ...
Unpacking quanser-license-manager (1.25.062-1) ...
Selecting previously unselected package quarc-runtime.
Preparing to unpack .../quarc-runtime_1.25.062-1_amd64.deb ...
Unpacking quarc-runtime (1.25.062-1) ...
Selecting previously unselected package qlabs-unreal.
Preparing to unpack .../qlabs-unreal_1.25.062-1_amd64.deb ...
Unpacking qlabs-unreal (1.25.062-1) ...
Setting up quanser-license-manager (1.25.062-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/quanser_license_manager.service → /usr/lib/systemd/system/quanser_license_manager.service.
Setting up quarc-runtime (1.25.062-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/quarc_target_manager.service → /usr/lib/systemd/system/quarc_target_manager.service.
Setting up qlabs-unreal (1.25.062-1) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for shared-mime-info (2.4-4) ...
`

**Comment by jsp20** [comment]
Hey @kubanond just to confirm..... Were you able to spawn the QCar2? You opened https://github.com/quanser/ACC-Competition-2025/issues/9 related to the minimum hardware requirements and the performance of your QCar2. Are these two questions related?

**Comment by kubanond** [comment]
I was able to spawn the QCar2 in the studio so i spawned it there and test the other stuff, so the problem with spawning the QCar in the plane remains. So these issues are not related @jsp20
